services:
  app:
    container_name: bluecrm-api
    build: .
    expose:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true